---
- name: test debug massege
  hosts: all
  tasks: 
   - name: run ls command
     command: ls -ltra
     register: testvar
   - name: using debug
     debug:
      msg: this the the end of massages
   - debug:
      var: testvar
